name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ggok:latest . 
    - name: Docker Login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: List Images
      run: docker images
    - name: tag Images
      run: docker tag ggok:latest ${{ secrets.DOCKER_USERNAME }}/ggok:latest
    - name: Push Images 
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ggok:latest
